Imports DevExpress.XtraPivotGrid
Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Drawing
Imports System.Linq
Imports System.Text
Imports System.Threading.Tasks
Imports System.Windows.Forms

Namespace CustomGroupIntervals
	Partial Public Class Form1
		Inherits Form

		Public Sub New()
			InitializeComponent()
			' This line of code is generated by Data Source Configuration Wizard
			' Fill the ExcelDataSource asynchronously
			excelDataSource1.FillAsync()
			' This line of code is generated by Data Source Configuration Wizard
			' Fill the ExcelDataSource asynchronously
			excelDataSource1.FillAsync()

			Dim pivotGridFieldCountry As New PivotGridField()
			pivotGridFieldCountry.Area = PivotArea.ColumnArea
			Dim country As New DataSourceColumnBinding("Country")
			pivotGridFieldCountry.DataBinding = country
			pivotGridControl1.Fields.Add(pivotGridFieldCountry)

			Dim pivotGridFieldProducts As New PivotGridField()
			pivotGridFieldProducts.Area = PivotArea.RowArea
			Dim productNames As New DataSourceColumnBinding("ProductName")
			pivotGridFieldProducts.DataBinding = productNames
			pivotGridFieldProducts.Name = "fieldProductName"
			pivotGridControl1.Fields.Add(pivotGridFieldProducts)

			Dim pivotGridFieldGroups As New PivotGridField()
			pivotGridFieldGroups.Area = PivotArea.RowArea
			pivotGridFieldGroups.Caption = "Product Groups"
			pivotGridFieldGroups.Options.ShowExpressionEditorMenu = True
			Dim customInterval As New ExpressionDataBinding("Iif(Substring([fieldProductName], 0, 1) < 'F', 
				'A-E', Substring([fieldProductName], 0, 1) < 'T', 'F-S', 'T-Z')")
			pivotGridFieldGroups.DataBinding = customInterval
			pivotGridFieldGroups.AreaIndex = 0
			pivotGridControl1.Fields.Add(pivotGridFieldGroups)

			Dim pivotGridFieldSales As New PivotGridField()
			pivotGridFieldSales.Area = PivotArea.DataArea
			Dim extendedPrice As New DataSourceColumnBinding("Extended Price")
			pivotGridFieldSales.DataBinding = extendedPrice
			pivotGridControl1.Fields.Add(pivotGridFieldSales)

		End Sub
	End Class
End Namespace
