Imports DevExpress.XtraPivotGrid
Imports System.Windows.Forms

Namespace CustomGroupIntervals

    Public Partial Class Form1
        Inherits Form

        Public Sub New()
            InitializeComponent()
            ' This line of code is generated by Data Source Configuration Wizard
            ' Fill the ExcelDataSource asynchronously
            excelDataSource1.FillAsync()
            ' This line of code is generated by Data Source Configuration Wizard
            ' Fill the ExcelDataSource asynchronously
            excelDataSource1.FillAsync()
            Dim pivotGridFieldCountry As PivotGridField = New PivotGridField()
            pivotGridFieldCountry.Area = PivotArea.ColumnArea
            Dim country As DataSourceColumnBinding = New DataSourceColumnBinding("Country")
            pivotGridFieldCountry.DataBinding = country
            pivotGridControl1.Fields.Add(pivotGridFieldCountry)
            Dim pivotGridFieldProducts As PivotGridField = New PivotGridField()
            pivotGridFieldProducts.Area = PivotArea.RowArea
            Dim productNames As DataSourceColumnBinding = New DataSourceColumnBinding("ProductName")
            pivotGridFieldProducts.DataBinding = productNames
            pivotGridFieldProducts.Name = "fieldProductName"
            pivotGridControl1.Fields.Add(pivotGridFieldProducts)
            Dim pivotGridFieldGroups As PivotGridField = New PivotGridField()
            pivotGridFieldGroups.Area = PivotArea.RowArea
            pivotGridFieldGroups.Caption = "Product Groups"
            pivotGridFieldGroups.Options.ShowExpressionEditorMenu = True
            Dim customInterval As ExpressionDataBinding = New ExpressionDataBinding("Iif(Substring([fieldProductName], 0, 1) < 'F'," & " 'A-E', Substring([fieldProductName], 0, 1) < 'T', 'F-S', 'T-Z')")
            pivotGridFieldGroups.DataBinding = customInterval
            pivotGridFieldGroups.AreaIndex = 0
            pivotGridControl1.Fields.Add(pivotGridFieldGroups)
            Dim pivotGridFieldSales As PivotGridField = New PivotGridField()
            pivotGridFieldSales.Area = PivotArea.DataArea
            Dim extendedPrice As DataSourceColumnBinding = New DataSourceColumnBinding("Extended Price")
            pivotGridFieldSales.DataBinding = extendedPrice
            pivotGridControl1.Fields.Add(pivotGridFieldSales)
        End Sub
    End Class
End Namespace
