using DevExpress.XtraPivotGrid;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace CustomGroupIntervals {
    public partial class Form1 : Form {
        public Form1() {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the ExcelDataSource asynchronously
            excelDataSource1.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the ExcelDataSource asynchronously
            excelDataSource1.FillAsync();

            PivotGridField pivotGridFieldCountry = new PivotGridField();
            pivotGridFieldCountry.Area = PivotArea.ColumnArea;
            DataSourceColumnBinding country = new DataSourceColumnBinding("Country");
            pivotGridFieldCountry.DataBinding = country;
            pivotGridControl1.Fields.Add(pivotGridFieldCountry);


            PivotGridField pivotGridFieldProducts = new PivotGridField();
            pivotGridFieldProducts.Area = PivotArea.RowArea;
            DataSourceColumnBinding productNames = new DataSourceColumnBinding("ProductName");
            pivotGridFieldProducts.DataBinding = productNames;
            pivotGridFieldProducts.Name = "fieldProductName";
            pivotGridControl1.Fields.Add(pivotGridFieldProducts);

            PivotGridField pivotGridFieldGroups = new PivotGridField();
            pivotGridFieldGroups.Area = PivotArea.RowArea;
            pivotGridFieldGroups.Caption = "Product Groups";
            pivotGridFieldGroups.Options.ShowExpressionEditorMenu = true;
            ExpressionDataBinding customInterval = new ExpressionDataBinding("Iif(Substring([fieldProductName], 0, 1) < 'F', 'A-E', Substring([fieldProductName], 0, 1) < 'T', 'F-S', 'T-Z')");
            pivotGridFieldGroups.DataBinding = customInterval;
            pivotGridFieldGroups.AreaIndex = 0;
            pivotGridControl1.Fields.Add(pivotGridFieldGroups);


            PivotGridField pivotGridFieldSales = new PivotGridField();
            pivotGridFieldSales.Area = PivotArea.DataArea;
            DataSourceColumnBinding extendedPrice = new DataSourceColumnBinding("Extended Price");
            pivotGridFieldSales.DataBinding = extendedPrice;
            pivotGridControl1.Fields.Add(pivotGridFieldSales);

        }
    }
}
